version: "3.8"
services:
    workspace:
        image: fernandobenayas/spark-workspace:1.0
        container_name: workspace
        ports: 
            - "6006"
        networks:
            - sparknet
        deploy:
            restart_policy:
                condition: on-failure
        volumes:
            - ../tmp/eonet_api.json:/opt/eonet_api.json
    spark-master:
        image: fernandobenayas/spark-master:1.0
        container_name: spark-master
        ports: 
            - "4040:4040"
            - "8080:8080"
            - "18080:18080"
            - "7077"
        networks:
            - sparknet
        env_file: 
            - master.env
        deploy:
            restart_policy:
                condition: on-failure
        volumes:
            - ../tmp/eonet_api.json:/opt/eonet_api.json
    spark-worker-1:
        image: fernandobenayas/spark-worker:1.0
        container_name: spark-worker-1
        ports: 
            - "8081:8081"
            - "7077"
        networks:
            - sparknet
        env_file: 
            - worker.env
        deploy:
            restart_policy:
                condition: on-failure
        volumes:
            - ../tmp/eonet_api.json:/opt/eonet_api.json
    spark-worker-2:
        image: fernandobenayas/spark-worker:1.0
        container_name: spark-worker-2
        ports: 
            - "8082:8081"
            - "7077"
        networks:
            - sparknet
        env_file: 
            - worker.env
        deploy:
            restart_policy:
                condition: on-failure
        volumes:
            - ../tmp/eonet_api.json:/opt/eonet_api.json
networks:
    sparknet: